### PR TITLE
MNT/FIX: migrate to latest standards and fix documentation building

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Upgrading by way of https://github.com/pcdshub/pcds-python-migration-tools
* pcdsutils has been migrated to use setuptools-scm, replacing versioneer, as its version-string management tool of choice.
* pcdsutils has been migrated to use the modern ``pyproject.toml``, replacing ``setup.py`` and related files.
* Older language features and syntax found in the repository have been updated to Python 3.9+ standards by way of ``pyupgrade``.
* Sphinx 6.0 is now supported for documentation building. ``docs-versions-menu`` replaces ``doctr-versions-menu`` and ``doctr`` usage for documentation deployment on GitHub Actions.  The deployment key is now no longer required.
* `pyupgrade` was used to update annotations, though there might not have been many here
* `pycln` was used to clean up imports
* Some manual fixes were required to fix up style
* Made `pyqtcss` to be a proper submodule
* Made `pyqtcss` be optional - because you might fail to recursively clone this repo
* Added `jet-tracking` entrypoint
* Added `jet_tracking.__main__` for usage with `python -m jet_tracking`
* Changed internal imports to be relative imports
* Removed `sys.path` modifications where possible
* Removed ancient docs stuff. Should be building now.
* Migrated repository settings to GitHub Actions passing requirement for PR merging.

## Motivation and Context
* Migrating because we want to migrate our projects from Travis CI for one.

## How Has This Been Tested?
* GitHub Actions - but the test suite does not have any real functionality
* Launched locally

## Screenshot

Works outside of psbuild-rhel7, for example on my macbook:

image

### CODE REVIEW

**Comment by klauer** [comment]
I think this is going to pass CI finally.

My primary goal here was to get our documentation building pipeline functioning again, but it took a bit more tweaking to get there than anticipated.

**Review by tangkong — APPROVED** [review]
This looks good to me I think.  Covers the most recent changes to the ci-helpers, and tests pass (docs build) so I'm largely satisfied.

**Review by vespos — APPROVED** [review]
Looks good to me!
Thanks a lot for cleaning up this repo, which had been left in disarray a little bit

**Review by ZLLentz — COMMENTED** [review]
All the changes look clean and the built docs are downloadable from the github actions build :+1:

One quibble: the docs credits/authors page is incomplete. I noticed this when flipping through the docs build.
https://github.com/pcdshub/jet_tracking/blob/master/docs/source/authors.rst

image

**Comment by ZLLentz** [comment]
Should we merge this?

**Comment by klauer** [comment]
I have nothing further to add here; @amandashack ?

**Pull request merged**
