### PR TITLE
ENH: add bluesky scans from late 2018

### PR DESCRIPTION
**Pull request by klauer**

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Looks like this has the first three commits from #12?

**Comment by klauer** [comment]
Yes, merged that one first.

Also https://github.com/klauer/jet_tracking/commit/c64f696c08e2b2f12215462cc8d384e860eb7531 has our wiggle test code that I had used to generate the video that confused everyone

**Comment by klauer** [comment]
Failing on flake8

**Comment by ZryletTC** [comment]
@klauer Is this PR no longer relevant?

**Comment by klauer** [comment]
The scientists chose to go another way. The branch will remain on my fork, but should not be merged.

**Comment by ZryletTC** [comment]
Got it, what about #14?

**Comment by klauer** [comment]
Almost the same, with the exception that it exists on a ex-PCDS member's branch and should probably be copied somewhere for reference.

**Comment by ZryletTC** [comment]
Got it, copying to my fork for now.

**Pull request closed without merging**
